name: Demo workflow
on: workflow_dispatch
jobs:
     print:
           runs-on: macos-latest
           steps:
                 - name: Print greeting
                    run: echo "Hi, Merion!"
                       
                     
